# train.submit
# HTCondor submit file for FLAN-T5 style-transfer training

universe        = vanilla
initialdir = /home/svdighe/text_style_transfer
executable = /home/svdighe/text_style_transfer/train_conda_wrapper.sh

arguments       =

# Required files
transfer_input_files = /home/svdighe/text_style_transfer/train_conda_wrapper.sh, \
                      /home/svdighe/text_style_transfer/scripts/train_model.py, \
                      /home/svdighe/text_style_transfer/data/processed_data/train.jsonl, \
                      /home/svdighe/text_style_transfer/data/processed_data/val.jsonl, \
                      /home/svdighe/text_style_transfer/data/processed_data/test.jsonl

# File transfer behavior
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_executable     = TRUE

# Logging
log     = logs/train_$(Cluster)_$(Process).log
output  = logs/train_$(Cluster)_$(Process).out
error   = logs/train_$(Cluster)_$(Process).err

# Resource requests
# request_cpus    = 4
request_memory  = 64 GB
+request_gpus       = 1

queue 1
